service: users

plugins:
  - serverless-webpack
  - serverless-finch

custom:
  webpack: ./config/webpack/serverless.js
  webpackIncludeModules:
      packagePath: './package.json'
  client:
    bucketName: ${self:service}-${opt:stage, self:provider.stage}-static
    distributionFolder: static-dist

provider:
  name: aws
  runtime: nodejs6.10
  region: eu-west-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Scan
        - dynamodb:PutItem
        - dynamodb:UpdateItem
      Resource:
        - { "Fn::GetAtt": ["TOPWSUsers", "Arn"] }
    - Effect: Allow
      Action:
        - dynamodb:GetItem
        - dynamodb:PutItem
      Resource:
        - { "Fn::GetAtt": ["TOPWSConfig", "Arn"] }
  environment:
    TABLE_USERS: { "Ref": "TOPWSUsers" }
    TABLE_CONFIGURATION: { "Ref": "TOPWSConfig" }

functions:
  list:
    handler: users/online.list
    events:
      - http:
          path: users
          method: get
          cors: true
  vote:
    handler: users/online.vote
    events:
      - http:
          path: users/{userId}/vote
          method: put
          cors: true
          request:
            parameters:
              paths:
                userId: true
  scrape:
    handler: users/batch.scrape
  get:
    handler: users/configuration.get
    events:
      - http:
          path: config/{configKey}
          method: get
          cors: true
          request:
            parameters:
              paths:
                configKey: true
  set:
    handler: users/configuration.set
    events:
      - http:
          path: config
          method: post
          cors: true

resources:
  Resources:
    TOPWSUsers:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    TOPWSConfig:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: key
            AttributeType: S
        KeySchema:
          - AttributeName: key
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
